### ISSUE TITLE
Two records of the same component appear in the list “I Install ”

### ISSUE THREAD

**Issue by littsummer** [kubebb/core#388]
Two records of the same component appear in the list “I Install ”，but updated at different times @Abirdcfly 
The data that was updated earlier flashed.
![image](https://github.com/kubebb/core/assets/41468710/f704fc6d-c615-4608-a3ca-7fbcb4cdb18f)

**Comment by bjwswang** [comment]
@littsummer seems this is  a bug in component-store. @dayuy

**Comment by Abirdcfly** [comment]
This bug is caused by someone installing the chartmuseum via cpl, then uninstalling it via helm   manually, and then installing a new chartmuseum with another cpl.

That is to say, we need to deal with the situation where the cpl's corresponding chart is manually uninstalled or updated by the helm command
